import React from "react"
import ReactDOM from "react-dom"
import NetworkChart from "../src/index.jsx"

class ExampleApp extends React.Component {

  constructor(props) {
    super(props)
    this.state = {
      nodes1: [
        {"id": "Myriel", "group": 1, "nodeSize": 2},
        {"id": "Napoleon", "group": 1, "nodeSize": 5},
        {"id": "Mlle.Baptistine", "group": 1, "nodeSize": 9},
        {"id": "Mme.Magloire", "group": 1, "nodeSize": 3},
        {"id": "CountessdeLo", "group": 1, "nodeSize": 2},
        {"id": "Geborand", "group": 1, "nodeSize": 15},
        {"id": "Champtercier", "group": 1, "nodeSize": 4},
        {"id": "Cravatte", "group": 1, "nodeSize": 5},
        {"id": "Count", "group": 1, "nodeSize": 7},
        {"id": "OldMan", "group": 1, "nodeSize": 8},
        {"id": "Labarre", "group": 2, "nodeSize": 3},
        {"id": "Valjean", "group": 2, "nodeSize": 1},
        {"id": "Marguerite", "group": 3, "nodeSize": 2},
        {"id": "Mme.deR", "group": 2, "nodeSize": 5},
        {"id": "Isabeau", "group": 2, "nodeSize": 12},
        {"id": "Gervais", "group": 2, "nodeSize": 13},
        {"id": "Tholomyes", "group": 3, "nodeSize": 7},
        {"id": "Listolier", "group": 3, "nodeSize": 6},
        {"id": "Fameuil", "group": 3, "nodeSize": 5},
        {"id": "Blacheville", "group": 3, "nodeSize": 4},
        {"id": "Favourite", "group": 3, "nodeSize": 3},
        {"id": "Dahlia", "group": 3, "nodeSize": 2},
        {"id": "Zephine", "group": 3, "nodeSize": 10},
        {"id": "Fantine", "group": 3, "nodeSize": 9},
        {"id": "Mme.Thenardier", "group": 4, "nodeSize": 3},
        {"id": "Thenardier", "group": 4, "nodeSize": 4},
        {"id": "Cosette", "group": 5, "nodeSize": 5},
        {"id": "Javert", "group": 4, "nodeSize": 4},
        {"id": "Fauchelevent", "group": 0, "nodeSize": 5},
        {"id": "Bamatabois", "group": 2, "nodeSize": 6},
        {"id": "Perpetue", "group": 3, "nodeSize": 8},
        {"id": "Simplice", "group": 2, "nodeSize": 1},
        {"id": "Scaufflaire", "group": 2, "nodeSize": 8},
        {"id": "Woman1", "group": 2, "nodeSize": 9},
        {"id": "Judge", "group": 2, "nodeSize": 7},
        {"id": "Champmathieu", "group": 2, "nodeSize": 10},
        {"id": "Brevet", "group": 2, "nodeSize": 2},
        {"id": "Chenildieu", "group": 2, "nodeSize": 1},
        {"id": "Cochepaille", "group": 2, "nodeSize": 5},
        {"id": "Pontmercy", "group": 4, "nodeSize": 6},
        {"id": "Boulatruelle", "group": 6, "nodeSize": 7},
        {"id": "Eponine", "group": 4, "nodeSize": 8},
        {"id": "Anzelma", "group": 4, "nodeSize": 9},
        {"id": "Woman2", "group": 5, "nodeSize": 1},
        {"id": "MotherInnocent", "group": 0, "nodeSize": 2},
        {"id": "Gribier", "group": 0, "nodeSize": 2},
        {"id": "Jondrette", "group": 7, "nodeSize": 3},
        {"id": "Mme.Burgon", "group": 7, "nodeSize": 5},
        {"id": "Gavroche", "group": 8, "nodeSize": 7},
        {"id": "Gillenormand", "group": 5, "nodeSize": 10},
        {"id": "Magnon", "group": 5, "nodeSize": 4},
        {"id": "Mlle.Gillenormand", "group": 5, "nodeSize": 5},
        {"id": "Mme.Pontmercy", "group": 5, "nodeSize": 6},
        {"id": "Mlle.Vaubois", "group": 5, "nodeSize": 6},
        {"id": "Lt.Gillenormand", "group": 5, "nodeSize": 8},
        {"id": "Marius", "group": 8, "nodeSize": 3},
        {"id": "BaronessT", "group": 5, "nodeSize": 4},
        {"id": "Mabeuf", "group": 8, "nodeSize": 5},
        {"id": "Enjolras", "group": 8, "nodeSize": 7},
        {"id": "Combeferre", "group": 8, "nodeSize": 9},
        {"id": "Prouvaire", "group": 8, "nodeSize": 8},
        {"id": "Feuilly", "group": 8, "nodeSize": 2},
        {"id": "Courfeyrac", "group": 8, "nodeSize": 3},
        {"id": "Bahorel", "group": 8, "nodeSize": 11},
        {"id": "Bossuet", "group": 8, "nodeSize": 9},
        {"id": "Joly", "group": 8, "nodeSize": 2},
        {"id": "Grantaire", "group": 8, "nodeSize": 5},
        {"id": "MotherPlutarch", "group": 9, "nodeSize": 8},
        {"id": "Gueulemer", "group": 4, "nodeSize": 7},
        {"id": "Babet", "group": 4, "nodeSize": 6},
        {"id": "Claquesous", "group": 4, "nodeSize": 6},
        {"id": "Montparnasse", "group": 4, "nodeSize": 5},
        {"id": "Toussaint", "group": 5, "nodeSize": 4},
        {"id": "Child1", "group": 10, "nodeSize": 3},
        {"id": "Child2", "group": 10, "nodeSize": 2},
        {"id": "Brujon", "group": 4, "nodeSize": 1},
        {"id": "Mme.Hucheloup", "group": 8, "nodeSize": 1}
      ],
      links1: [
        {parent: "Napoleon", child: "Myriel", "value": 1},
        {parent: "Mlle.Baptistine", child: "Myriel", "value": 8},
        {parent: "Mme.Magloire", child: "Myriel", "value": 10},
        {parent: "Mme.Magloire", child: "Mlle.Baptistine", "value": 6},
        {parent: "CountessdeLo", child: "Myriel", "value": 1},
        {parent: "Geborand", child: "Myriel", "value": 1},
        {parent: "Champtercier", child: "Myriel", "value": 1},
        {parent: "Cravatte", child: "Myriel", "value": 1},
        {parent: "Count", child: "Myriel", "value": 2},
        {parent: "OldMan", child: "Myriel", "value": 1},
        {parent: "Valjean", child: "Labarre", "value": 1},
        {parent: "Valjean", child: "Mme.Magloire", "value": 3},
        {parent: "Valjean", child: "Mlle.Baptistine", "value": 3},
        {parent: "Valjean", child: "Myriel", "value": 5},
        {parent: "Marguerite", child: "Valjean", "value": 1},
        {parent: "Mme.deR", child: "Valjean", "value": 1},
        {parent: "Isabeau", child: "Valjean", "value": 1},
        {parent: "Gervais", child: "Valjean", "value": 1},
        {parent: "Listolier", child: "Tholomyes", "value": 4},
        {parent: "Fameuil", child: "Tholomyes", "value": 4},
        {parent: "Fameuil", child: "Listolier", "value": 4},
        {parent: "Blacheville", child: "Tholomyes", "value": 4},
        {parent: "Blacheville", child: "Listolier", "value": 4},
        {parent: "Blacheville", child: "Fameuil", "value": 4},
        {parent: "Favourite", child: "Tholomyes", "value": 3},
        {parent: "Favourite", child: "Listolier", "value": 3},
        {parent: "Favourite", child: "Fameuil", "value": 3},
        {parent: "Favourite", child: "Blacheville", "value": 4},
        {parent: "Dahlia", child: "Tholomyes", "value": 3},
        {parent: "Dahlia", child: "Listolier", "value": 3},
        {parent: "Dahlia", child: "Fameuil", "value": 3},
        {parent: "Dahlia", child: "Blacheville", "value": 3},
        {parent: "Dahlia", child: "Favourite", "value": 5},
        {parent: "Zephine", child: "Tholomyes", "value": 3},
        {parent: "Zephine", child: "Listolier", "value": 3},
        {parent: "Zephine", child: "Fameuil", "value": 3},
        {parent: "Zephine", child: "Blacheville", "value": 3},
        {parent: "Zephine", child: "Favourite", "value": 4},
        {parent: "Zephine", child: "Dahlia", "value": 4},
        {parent: "Fantine", child: "Tholomyes", "value": 3},
        {parent: "Fantine", child: "Listolier", "value": 3},
        {parent: "Fantine", child: "Fameuil", "value": 3},
        {parent: "Fantine", child: "Blacheville", "value": 3},
        {parent: "Fantine", child: "Favourite", "value": 4},
        {parent: "Fantine", child: "Dahlia", "value": 4},
        {parent: "Fantine", child: "Zephine", "value": 4},
        {parent: "Fantine", child: "Marguerite", "value": 2},
        {parent: "Fantine", child: "Valjean", "value": 9},
        {parent: "Mme.Thenardier", child: "Fantine", "value": 2},
        {parent: "Mme.Thenardier", child: "Valjean", "value": 7},
        {parent: "Thenardier", child: "Mme.Thenardier", "value": 13},
        {parent: "Thenardier", child: "Fantine", "value": 1},
        {parent: "Thenardier", child: "Valjean", "value": 12},
        {parent: "Cosette", child: "Mme.Thenardier", "value": 4},
        {parent: "Cosette", child: "Valjean", "value": 31},
        {parent: "Cosette", child: "Tholomyes", "value": 1},
        {parent: "Cosette", child: "Thenardier", "value": 1},
        {parent: "Javert", child: "Valjean", "value": 17},
        {parent: "Javert", child: "Fantine", "value": 5},
        {parent: "Javert", child: "Thenardier", "value": 5},
        {parent: "Javert", child: "Mme.Thenardier", "value": 1},
        {parent: "Javert", child: "Cosette", "value": 1},
        {parent: "Fauchelevent", child: "Valjean", "value": 8},
        {parent: "Fauchelevent", child: "Javert", "value": 1},
        {parent: "Bamatabois", child: "Fantine", "value": 1},
        {parent: "Bamatabois", child: "Javert", "value": 1},
        {parent: "Bamatabois", child: "Valjean", "value": 2},
        {parent: "Perpetue", child: "Fantine", "value": 1},
        {parent: "Simplice", child: "Perpetue", "value": 2},
        {parent: "Simplice", child: "Valjean", "value": 3},
        {parent: "Simplice", child: "Fantine", "value": 2},
        {parent: "Simplice", child: "Javert", "value": 1},
        {parent: "Scaufflaire", child: "Valjean", "value": 1},
        {parent: "Woman1", child: "Valjean", "value": 2},
        {parent: "Woman1", child: "Javert", "value": 1},
        {parent: "Judge", child: "Valjean", "value": 3},
        {parent: "Judge", child: "Bamatabois", "value": 2},
        {parent: "Champmathieu", child: "Valjean", "value": 3},
        {parent: "Champmathieu", child: "Judge", "value": 3},
        {parent: "Champmathieu", child: "Bamatabois", "value": 2},
        {parent: "Brevet", child: "Judge", "value": 2},
        {parent: "Brevet", child: "Champmathieu", "value": 2},
        {parent: "Brevet", child: "Valjean", "value": 2},
        {parent: "Brevet", child: "Bamatabois", "value": 1},
        {parent: "Chenildieu", child: "Judge", "value": 2},
        {parent: "Chenildieu", child: "Champmathieu", "value": 2},
        {parent: "Chenildieu", child: "Brevet", "value": 2},
        {parent: "Chenildieu", child: "Valjean", "value": 2},
        {parent: "Chenildieu", child: "Bamatabois", "value": 1},
        {parent: "Cochepaille", child: "Judge", "value": 2},
        {parent: "Cochepaille", child: "Champmathieu", "value": 2},
        {parent: "Cochepaille", child: "Brevet", "value": 2},
        {parent: "Cochepaille", child: "Chenildieu", "value": 2},
        {parent: "Cochepaille", child: "Valjean", "value": 2},
        {parent: "Cochepaille", child: "Bamatabois", "value": 1},
        {parent: "Pontmercy", child: "Thenardier", "value": 1},
        {parent: "Boulatruelle", child: "Thenardier", "value": 1},
        {parent: "Eponine", child: "Mme.Thenardier", "value": 2},
        {parent: "Eponine", child: "Thenardier", "value": 3},
        {parent: "Anzelma", child: "Eponine", "value": 2},
        {parent: "Anzelma", child: "Thenardier", "value": 2},
        {parent: "Anzelma", child: "Mme.Thenardier", "value": 1},
        {parent: "Woman2", child: "Valjean", "value": 3},
        {parent: "Woman2", child: "Cosette", "value": 1},
        {parent: "Woman2", child: "Javert", "value": 1},
        {parent: "MotherInnocent", child: "Fauchelevent", "value": 3},
        {parent: "MotherInnocent", child: "Valjean", "value": 1},
        {parent: "Gribier", child: "Fauchelevent", "value": 2},
        {parent: "Mme.Burgon", child: "Jondrette", "value": 1},
        {parent: "Gavroche", child: "Mme.Burgon", "value": 2},
        {parent: "Gavroche", child: "Thenardier", "value": 1},
        {parent: "Gavroche", child: "Javert", "value": 1},
        {parent: "Gavroche", child: "Valjean", "value": 1},
        {parent: "Gillenormand", child: "Cosette", "value": 3},
        {parent: "Gillenormand", child: "Valjean", "value": 2},
        {parent: "Magnon", child: "Gillenormand", "value": 1},
        {parent: "Magnon", child: "Mme.Thenardier", "value": 1},
        {parent: "Mlle.Gillenormand", child: "Gillenormand", "value": 9},
        {parent: "Mlle.Gillenormand", child: "Cosette", "value": 2},
        {parent: "Mlle.Gillenormand", child: "Valjean", "value": 2},
        {parent: "Mme.Pontmercy", child: "Mlle.Gillenormand", "value": 1},
        {parent: "Mme.Pontmercy", child: "Pontmercy", "value": 1},
        {parent: "Mlle.Vaubois", child: "Mlle.Gillenormand", "value": 1},
        {parent: "Lt.Gillenormand", child: "Mlle.Gillenormand", "value": 2},
        {parent: "Lt.Gillenormand", child: "Gillenormand", "value": 1},
        {parent: "Lt.Gillenormand", child: "Cosette", "value": 1},
        {parent: "Marius", child: "Mlle.Gillenormand", "value": 6},
        {parent: "Marius", child: "Gillenormand", "value": 12},
        {parent: "Marius", child: "Pontmercy", "value": 1},
        {parent: "Marius", child: "Lt.Gillenormand", "value": 1},
        {parent: "Marius", child: "Cosette", "value": 21},
        {parent: "Marius", child: "Valjean", "value": 19},
        {parent: "Marius", child: "Tholomyes", "value": 1},
        {parent: "Marius", child: "Thenardier", "value": 2},
        {parent: "Marius", child: "Eponine", "value": 5},
        {parent: "Marius", child: "Gavroche", "value": 4},
        {parent: "BaronessT", child: "Gillenormand", "value": 1},
        {parent: "BaronessT", child: "Marius", "value": 1},
        {parent: "Mabeuf", child: "Marius", "value": 1},
        {parent: "Mabeuf", child: "Eponine", "value": 1},
        {parent: "Mabeuf", child: "Gavroche", "value": 1},
        {parent: "Enjolras", child: "Marius", "value": 7},
        {parent: "Enjolras", child: "Gavroche", "value": 7},
        {parent: "Enjolras", child: "Javert", "value": 6},
        {parent: "Enjolras", child: "Mabeuf", "value": 1},
        {parent: "Enjolras", child: "Valjean", "value": 4},
        {parent: "Combeferre", child: "Enjolras", "value": 15},
        {parent: "Combeferre", child: "Marius", "value": 5},
        {parent: "Combeferre", child: "Gavroche", "value": 6},
        {parent: "Combeferre", child: "Mabeuf", "value": 2},
        {parent: "Prouvaire", child: "Gavroche", "value": 1},
        {parent: "Prouvaire", child: "Enjolras", "value": 4},
        {parent: "Prouvaire", child: "Combeferre", "value": 2},
        {parent: "Feuilly", child: "Gavroche", "value": 2},
        {parent: "Feuilly", child: "Enjolras", "value": 6},
        {parent: "Feuilly", child: "Prouvaire", "value": 2},
        {parent: "Feuilly", child: "Combeferre", "value": 5},
        {parent: "Feuilly", child: "Mabeuf", "value": 1},
        {parent: "Feuilly", child: "Marius", "value": 1},
        {parent: "Courfeyrac", child: "Marius", "value": 9},
        {parent: "Courfeyrac", child: "Enjolras", "value": 17},
        {parent: "Courfeyrac", child: "Combeferre", "value": 13},
        {parent: "Courfeyrac", child: "Gavroche", "value": 7},
        {parent: "Courfeyrac", child: "Mabeuf", "value": 2},
        {parent: "Courfeyrac", child: "Eponine", "value": 1},
        {parent: "Courfeyrac", child: "Feuilly", "value": 6},
        {parent: "Courfeyrac", child: "Prouvaire", "value": 3},
        {parent: "Bahorel", child: "Combeferre", "value": 5},
        {parent: "Bahorel", child: "Gavroche", "value": 5},
        {parent: "Bahorel", child: "Courfeyrac", "value": 6},
        {parent: "Bahorel", child: "Mabeuf", "value": 2},
        {parent: "Bahorel", child: "Enjolras", "value": 4},
        {parent: "Bahorel", child: "Feuilly", "value": 3},
        {parent: "Bahorel", child: "Prouvaire", "value": 2},
        {parent: "Bahorel", child: "Marius", "value": 1},
        {parent: "Bossuet", child: "Marius", "value": 5},
        {parent: "Bossuet", child: "Courfeyrac", "value": 12},
        {parent: "Bossuet", child: "Gavroche", "value": 5},
        {parent: "Bossuet", child: "Bahorel", "value": 4},
        {parent: "Bossuet", child: "Enjolras", "value": 10},
        {parent: "Bossuet", child: "Feuilly", "value": 6},
        {parent: "Bossuet", child: "Prouvaire", "value": 2},
        {parent: "Bossuet", child: "Combeferre", "value": 9},
        {parent: "Bossuet", child: "Mabeuf", "value": 1},
        {parent: "Bossuet", child: "Valjean", "value": 1},
        {parent: "Joly", child: "Bahorel", "value": 5},
        {parent: "Joly", child: "Bossuet", "value": 7},
        {parent: "Joly", child: "Gavroche", "value": 3},
        {parent: "Joly", child: "Courfeyrac", "value": 5},
        {parent: "Joly", child: "Enjolras", "value": 5},
        {parent: "Joly", child: "Feuilly", "value": 5},
        {parent: "Joly", child: "Prouvaire", "value": 2},
        {parent: "Joly", child: "Combeferre", "value": 5},
        {parent: "Joly", child: "Mabeuf", "value": 1},
        {parent: "Joly", child: "Marius", "value": 2},
        {parent: "Grantaire", child: "Bossuet", "value": 3},
        {parent: "Grantaire", child: "Enjolras", "value": 3},
        {parent: "Grantaire", child: "Combeferre", "value": 1},
        {parent: "Grantaire", child: "Courfeyrac", "value": 2},
        {parent: "Grantaire", child: "Joly", "value": 2},
        {parent: "Grantaire", child: "Gavroche", "value": 1},
        {parent: "Grantaire", child: "Bahorel", "value": 1},
        {parent: "Grantaire", child: "Feuilly", "value": 1},
        {parent: "Grantaire", child: "Prouvaire", "value": 1},
        {parent: "MotherPlutarch", child: "Mabeuf", "value": 3},
        {parent: "Gueulemer", child: "Thenardier", "value": 5},
        {parent: "Gueulemer", child: "Valjean", "value": 1},
        {parent: "Gueulemer", child: "Mme.Thenardier", "value": 1},
        {parent: "Gueulemer", child: "Javert", "value": 1},
        {parent: "Gueulemer", child: "Gavroche", "value": 1},
        {parent: "Gueulemer", child: "Eponine", "value": 1},
        {parent: "Babet", child: "Thenardier", "value": 6},
        {parent: "Babet", child: "Gueulemer", "value": 6},
        {parent: "Babet", child: "Valjean", "value": 1},
        {parent: "Babet", child: "Mme.Thenardier", "value": 1},
        {parent: "Babet", child: "Javert", "value": 2},
        {parent: "Babet", child: "Gavroche", "value": 1},
        {parent: "Babet", child: "Eponine", "value": 1},
        {parent: "Claquesous", child: "Thenardier", "value": 4},
        {parent: "Claquesous", child: "Babet", "value": 4},
        {parent: "Claquesous", child: "Gueulemer", "value": 4},
        {parent: "Claquesous", child: "Valjean", "value": 1},
        {parent: "Claquesous", child: "Mme.Thenardier", "value": 1},
        {parent: "Claquesous", child: "Javert", "value": 1},
        {parent: "Claquesous", child: "Eponine", "value": 1},
        {parent: "Claquesous", child: "Enjolras", "value": 1},
        {parent: "Montparnasse", child: "Javert", "value": 1},
        {parent: "Montparnasse", child: "Babet", "value": 2},
        {parent: "Montparnasse", child: "Gueulemer", "value": 2},
        {parent: "Montparnasse", child: "Claquesous", "value": 2},
        {parent: "Montparnasse", child: "Valjean", "value": 1},
        {parent: "Montparnasse", child: "Gavroche", "value": 1},
        {parent: "Montparnasse", child: "Eponine", "value": 1},
        {parent: "Montparnasse", child: "Thenardier", "value": 1},
        {parent: "Toussaint", child: "Cosette", "value": 2},
        {parent: "Toussaint", child: "Javert", "value": 1},
        {parent: "Toussaint", child: "Valjean", "value": 1},
        {parent: "Child1", child: "Gavroche", "value": 2},
        {parent: "Child2", child: "Gavroche", "value": 2},
        {parent: "Child2", child: "Child1", "value": 3},
        {parent: "Brujon", child: "Babet", "value": 3},
        {parent: "Brujon", child: "Gueulemer", "value": 3},
        {parent: "Brujon", child: "Thenardier", "value": 3},
        {parent: "Brujon", child: "Gavroche", "value": 1},
        {parent: "Brujon", child: "Eponine", "value": 1},
        {parent: "Brujon", child: "Claquesous", "value": 1},
        {parent: "Brujon", child: "Montparnasse", "value": 1},
        {parent: "Mme.Hucheloup", child: "Bossuet", "value": 1},
        {parent: "Mme.Hucheloup", child: "Joly", "value": 1},
        {parent: "Mme.Hucheloup", child: "Grantaire", "value": 1},
        {parent: "Mme.Hucheloup", child: "Bahorel", "value": 1},
        {parent: "Mme.Hucheloup", child: "Courfeyrac", "value": 1},
        {parent: "Mme.Hucheloup", child: "Gavroche", "value": 1},
        {parent: "Mme.Hucheloup", child: "Enjolras", "value": 1}
      ],
      nodes2: [
        {id: "Juliet", group: "Capulet"},
        {id: "Tybalt", group: "Capulet"},
        {id: "Lady Capulet", group: "Capulet"},
        {id: "Capulet", group: "Capulet"},
        {id: "Gregory", group: "Servants"},
        {id: "Sampson", group: "Servants"},
        {id: "Nurse", group: "Servants"},
        {id: "Peter", group: "Servants"},
        {id: "Romeo", group: "Montague"},
        {id: "Benvolio", group: "Montague"},
        {id: "Lady Montague", group: "Montague"},
        {id: "Montague", group: "Montague"},
        {id: "Balthasar", group: "Servants"},
        {id: "Abraham", group: "Servants"},
        {id: "Prince of Verona", group: "Verona"},
        {id: "Paris", group: "Verona"},
        {id: "Mercutio", group: "Verona"},
        {id: "Friar Lawrence", group: "Verona"},
        {id: "Friar John", group: "Verona"},
      ],
      links2: [
        {parent: "Juliet", child: "Tybalt"},
        {parent: "Juliet", child: "Lady Capulet"},
        {parent: "Juliet", child: "Capulet"},
        {parent: "Juliet", child: "Nurse"},
        {parent: "Juliet", child: "Romeo"},
        {parent: "Capulet", child: "Lady Capulet"},
        {parent: "Paris", child: "Juliet"},
        {parent: "Romeo", child: "Benvolio"},
        {parent: "Romeo", child: "Tybalt"},
        {parent: "Romeo", child: "Montague"},
        {parent: "Romeo", child: "Lady Montague"},
        {parent: "Romeo", child: "Balthasar"},
        {parent: "Romeo", child: "Mercutio"},
        {parent: "Montague", child: "Lady Montague"},
        {parent: "Tybalt", child: "Mercutio"},
        {parent: "Mercutio", child: "Prince of Verona"},
        {parent: "Paris", child: "Prince of Verona"},
        {parent: "Friar Lawrence", child: "Juliet"},
        {parent: "Friar Lawrence", child: "Romeo"},
        {parent: "Friar Lawrence", child: "Friar John"},
        {parent: "Nurse", child: "Gregory"},
        {parent: "Nurse", child: "Sampson"},
        {parent: "Nurse", child: "Peter"},
        {parent: "Balthasar", child: "Abraham"},
      ],
    }
  }

  render() {
    return(
      <div className="container"
        style={{textAlign:"center",fontFamily:"Open Sans"}}>
        <h1 style={{textAlign: "center"}}>Network Chart</h1>
        <div style={{width: "70%"}}>
          <NetworkChart
            nodes={this.state.nodes2}
            links={this.state.links2}
            labelKey="id"
            groupKey="group"
            nodeSize="off"
            nodeKey="nodeSize"/>
        </div>
      </div>
    )
  }
}


ReactDOM.render(
  <ExampleApp />,
  document.getElementById("react-app")
)
