import React from "react"
import ReactDOM from "react-dom"
import NetworkChart from "../src/index.jsx"

class ExampleApp extends React.Component {

  constructor(props) {
    super(props)
    this.state = {
      nodes: [
        {id: "Harry Potter", group: "Gryffindor", major: "Harry Potter"},
        {id: "Albus Dumbledore", group: "Staff", major: "Albus Dumbledore"}, //founder of order of phoenix
        {id: "Aberforth Dumbledore", group: "Dumbledore"},
        {id: "Ariana Dumbledore", group: "Dumbledore"},
        {id: "Bathilda Bagshot", group: "Staff"},
        {id: "Elphias Doge", group: "Order of the Phoenix"},
        {id: "Fawkes", group: "Pet"},
        {id: "Gellert Grindelwald", group: "Other"},
        {id: "Kendra Dumbledore", group: "Dumbledore"},
        {id: "Percival Dumbledore", group: "Dumbledore"},
        {id: "Professor Trelawney", group: "Staff"},
        {id: "Severus Snape", group: "Staff", major: "Severus Snape"},
        {id: "Barty Crouch Jr.", group: "Death Eaters"},
        {id: "Barty Crouch Sr.", group: "Ministry of Magic"},
        {id: "Alastor Moody", group: "Order of the Phoenix"},
        {id: "Dobby", group: "Other"},
        {id: "Bellatrix Lestrange", group: "Slytherin"},
        {id: "Dolores Umbridge", group: "Staff"},
        {id: "Ginny Weasley", group: "Gryffindor"},
        {id: "Arthur Weasley", group: "Gryffindor"},
        {id: "Bill Weasley", group: "Gryffindor"},
        {id: "Charlie Weasley", group: "Gryffindor"},
        {id: "Dean Thomas", group: "Gryffindor"},
        {id: "Fred Weasley", group: "Gryffindor"},
        {id: "George Weasley", group: "Gryffindor"},
        {id: "Lucius Malfoy", group: "Slytherin"},
        {id: "Michael Corner", group: "Ravenclaw"},
        {id: "Molly Weasley", group: "Gryffindor"},
        {id: "Ron Weasley", group: "Gryffindor", major: "Ron Weasley"},
        {id: "Hedwig", group: "Pet"},
        {id: "Hermione Granger", group: "Gryffindor", major: "Hermione Granger"},
        {id: "Crookshanks", group: "Pet"},
        {id: "Nagini", group: "Pet"},
        {id: "James Potter", group: "Gryffindor"},
        {id: "Lily Potter", group: "Gryffindor"},
        {id: "Petunia Dursley", group: "Dursley"},
        {id: "Vernon Dursley", group: "Dursley"},
        {id: "Dudley Dursley", group: "Dursley"},
        {id: "Romilda Vane", group: "Gryffindor"},
        {id: "Sirius Black", group: "Gryffindor"},
        {id: "Buckbeak", group: "Pet"},
        {id: "Cho Chang", group: "Ravenclaw"},
        {id: "Voldemort", group: "Slytherin", major: "Voldemort"},
        {id: "Armando Dippet", group: "Staff"},
        {id: "Bertha Jorkins", group: "Ministry of Magic"},
        {id: "Alicia Spinnet", group: "Gryffindor"},
        {id: "Angelina Johnson", group: "Gryffindor"},
        {id: "Anthony Goldstein", group: "Ravenclaw"},
        {id: "Colin Creevey", group: "Gryffindor"},
        {id: "Dennis Creevey", group: "Gryffindor"},
        {id: "Ernie Macmillian", group: "Hufflepuff"},
        {id: "Hannah Abbott", group: "Hufflepuff"},
        {id: "Justin Finch-Fletchley", group: "Hufflepuff"},
        {id: "Katie Bell", group: "Gryffindor"},
        {id: "Lavender Brown", group: "Gryffindor"},
        {id: "Lee Jordan", group: "Gryffindor"},
        {id: "Luna Lovegood", group: "Ravenclaw"},
        {id: "Neville Longbottom", group: "Gryffindor"},
        {id: "Padma Patil", group: "Ravenclaw"},
        {id: "Parvati Patil", group: "Gryffindor"},
        {id: "Seamus Finnigan", group: "Gryffindor"},
        {id: "Susan Bones", group: "Hufflepuff"},
        {id: "Terry Boot", group: "Ravenclaw"},
        {id: "Zacharias Smith", group: "Hufflepuff"},
        {id: "Draco Malfoy", group: "Slytherin"},
        {id: "Madam Rosmerta", group: "Hogsmeade"},
        {id: "Mr. Olivander", group: "Other"},
        {id: "Alice Longbottom", group: "Order of the Phoenix"},
        {id: "Arabella Figg", group: "Order of the Phoenix"},
        {id: "Caradoc Dearborn", group: "Order of the Phoenix"},
        {id: "Dedalus Diggle", group: "Order of the Phoenix"},
        {id: "Edgar Bones", group: "Order of the Phoenix"},
        {id: "Emmeline Vance", group: "Order of the Phoenix"},
        {id: "Fabian Prewett", group: "Order of the Phoenix"},
        {id: "Fleur Delacour", group: "Order of the Phoenix"},
        {id: "Frank Longbottom", group: "Order of the Phoenix"},
        {id: "Gideon Prewett", group: "Order of the Phoenix"},
        {id: "Hestia Jones", group: "Order of the Phoenix"},
        {id: "Kingsley Shacklebolt", group: "Order of the Phoenix"},
        {id: "Marlene McKinnon", group: "Order of the Phoenix"},
        {id: "Mundungus Fletcher", group: "Order of the Phoenix"},
        {id: "Nymphadora Tonks", group: "Order of the Phoenix"},
        {id: "Professor McGonagall", group: "Staff"},
        {id: "Remus Lupin", group: "Gryffindor"},
        {id: "Rubeus Hagrid", group: "Staff"},
        {id: "Sturgis Podmore", group: "Order of the Phoenix"},
        {id: "Viktor Krum", group: "Other"},
      ],
      links: [
        {parent: "Harry Potter", child: "Albus Dumbledore"},
        {parent: "Harry Potter", child: "Barty Crouch Jr."},
        {parent: "Harry Potter", child: "Dobby"},
        {parent: "Harry Potter", child: "Dolores Umbridge"},
        {parent: "Harry Potter", child: "Ginny Weasley"},
        {parent: "Harry Potter", child: "Hedwig"},
        {parent: "Harry Potter", child: "Hermione Granger"},
        {parent: "Harry Potter", child: "James Potter"},
        {parent: "Harry Potter", child: "Lily Potter"},
        {parent: "Harry Potter", child: "Nagini"},
        {parent: "Harry Potter", child: "Petunia Dursley"},
        {parent: "Harry Potter", child: "Vernon Dursley"},
        {parent: "Harry Potter", child: "Dudley Dursley"},
        {parent: "Harry Potter", child: "Professor Trelawney"},
        {parent: "Harry Potter", child: "Romilda Vane"},
        {parent: "Harry Potter", child: "Ron Weasley"},
        {parent: "Harry Potter", child: "Severus Snape"},
        {parent: "Harry Potter", child: "Sirius Black"},
        {parent: "Harry Potter", child: "Voldemort"},
        {parent: "Harry Potter", child: "Cho Chang"},
        {parent: "Harry Potter", child: "Mr. Olivander"},
        {parent: "Albus Dumbledore", child: "Aberforth Dumbledore"},
        {parent: "Albus Dumbledore", child: "Ariana Dumbledore"},
        {parent: "Albus Dumbledore", child: "Kendra Dumbledore"},
        {parent: "Albus Dumbledore", child: "Percival Dumbledore"},
        {parent: "Albus Dumbledore", child: "Bathilda Bagshot"},
        {parent: "Albus Dumbledore", child: "Elphias Doge"},
        {parent: "Albus Dumbledore", child: "Fawkes"},
        {parent: "Albus Dumbledore", child: "Gellert Grindelwald"},
        {parent: "Albus Dumbledore", child: "Harry Potter"},
        {parent: "Albus Dumbledore", child: "Severus Snape"},
        {parent: "Aberforth Dumbledore", child: "Ariana Dumbledore"},
        {parent: "Aberforth Dumbledore", child: "Kendra Dumbledore"},
        {parent: "Aberforth Dumbledore", child: "Percival Dumbledore"},
        {parent: "Barty Crouch Jr.", child: "Barty Crouch Sr."},
        {parent: "Barty Crouch Jr.", child: "Alastor Moody"},
        {parent: "Barty Crouch Jr.", child: "Alastor Moody"},
        {parent: "Dobby", child: "Bellatrix Lestrange"},
        {parent: "Ginny Weasley", child: "Arthur Weasley"},
        {parent: "Ginny Weasley", child: "Bill Weasley"},
        {parent: "Ginny Weasley", child: "Charlie Weasley"},
        {parent: "Ginny Weasley", child: "Dean Thomas"},
        {parent: "Ginny Weasley", child: "Fred Weasley"},
        {parent: "Ginny Weasley", child: "George Weasley"},
        {parent: "Ginny Weasley", child: "Lucius Malfoy"},
        {parent: "Ginny Weasley", child: "Michael Corner"},
        {parent: "Ginny Weasley", child: "Molly Weasley"},
        {parent: "Ginny Weasley", child: "Ron Weasley"},
        {parent: "Arthur Weasley", child: "Molly Weasley"},
        {parent: "Arthur Weasley", child: "Bill Weasley"},
        {parent: "Arthur Weasley", child: "Charlie Weasley"},
        {parent: "Arthur Weasley", child: "Fred Weasley"},
        {parent: "Arthur Weasley", child: "George Weasley"},
        {parent: "Arthur Weasley", child: "Ron Weasley"},
        {parent: "Bill Weasley", child: "Charlie Weasley"},
        {parent: "Bill Weasley", child: "Fred Weasley"},
        {parent: "Bill Weasley", child: "George Weasley"},
        {parent: "Bill Weasley", child: "Molly Weasley"},
        {parent: "Bill Weasley", child: "Ron Weasley"},
        {parent: "Charlie Weasley", child: "Fred Weasley"},
        {parent: "Charlie Weasley", child: "George Weasley"},
        {parent: "Charlie Weasley", child: "Molly Weasley"},
        {parent: "Charlie Weasley", child: "Ron Weasley"},
        {parent: "Fred Weasley", child: "George Weasley"},
        {parent: "Fred Weasley", child: "Molly Weasley"},
        {parent: "Fred Weasley", child: "Ron Weasley"},
        {parent: "George Weasley", child: "Molly Weasley"},
        {parent: "George Weasley", child: "Ron Weasley"},
        {parent: "Ron Weasley", child: "Molly Weasley"},
        {parent: "Hermione Granger", child: "Crookshanks"},
        {parent: "Hermione Granger", child: "Nagini"},
        {parent: "Hermione Granger", child: "Ron Weasley"},
        {parent: "Hermione Granger", child: "Viktor Krum"},
        {parent: "Hermione Granger", child: "Lily Potter"},
        {parent: "Hermione Granger", child: "Lucius Malfoy"},
        {parent: "James Potter", child: "Lily Potter"},
        {parent: "James Potter", child: "Voldemort"},
        {parent: "Lily Potter", child: "Petunia Dursley"},
        {parent: "Vernon Dursley", child: "Petunia Dursley"},
        {parent: "Vernon Dursley", child: "Dudley Dursley"},
        {parent: "Dudley Dursley", child: "Petunia Dursley"},
        {parent: "Professor Trelawney", child: "Severus Snape"},
        {parent: "Severus Snape", child: "George Weasley"},
        {parent: "Severus Snape", child: "Lily Potter"},
        {parent: "Severus Snape", child: "Voldemort"},
        {parent: "Sirius Black", child: "Bellatrix Lestrange"},
        {parent: "Sirius Black", child: "Buckbeak"},
        {parent: "Voldemort", child: "Armando Dippet"},
        {parent: "Voldemort", child: "Barty Crouch Jr."},
        {parent: "Voldemort", child: "Bathilda Bagshot"},
        {parent: "Voldemort", child: "Bertha Jorkins"},
        {parent: "Voldemort", child: "Gellert Grindelwald"},
        {parent: "Voldemort", child: "Lily Potter"},
        {parent: "Voldemort", child: "Nagini"},
        {parent: "Voldemort", child: "Mr. Olivander"},
        {parent: "Cho Chang", child: "Michael Corner"},
        {parent: "Katie Bell", child: "Draco Malfoy"},
        {parent: "Katie Bell", child: "Madam Rosmerta"},
        {parent: "Draco Malfoy", child: "Madam Rosmerta"},
        {parent: "Draco Malfoy", child: "Dobby"},
        {parent: "Neville Longbottom", child: "Nagini"},
        {parent: "Alicia Spinnet", child: "Angelina Johnson"},
        {parent: "Alicia Spinnet", child: "Anthony Goldstein"},
        {parent: "Alicia Spinnet", child: "Cho Chang"},
        {parent: "Alicia Spinnet", child: "Colin Creevey"},
        {parent: "Alicia Spinnet", child: "Dean Thomas"},
        {parent: "Alicia Spinnet", child: "Dennis Creevey"},
        {parent: "Alicia Spinnet", child: "Ernie Macmillian"},
        {parent: "Alicia Spinnet", child: "Fred Weasley"},
        {parent: "Alicia Spinnet", child: "George Weasley"},
        {parent: "Alicia Spinnet", child: "Ginny Weasley"},
        {parent: "Alicia Spinnet", child: "Hannah Abbott"},
        {parent: "Alicia Spinnet", child: "Harry Potter"},
        {parent: "Alicia Spinnet", child: "Hermione Granger"},
        {parent: "Alicia Spinnet", child: "Justin Finch-Fletchley"},
        {parent: "Alicia Spinnet", child: "Katie Bell"},
        {parent: "Alicia Spinnet", child: "Lavender Brown"},
        {parent: "Alicia Spinnet", child: "Lee Jordan"},
        {parent: "Alicia Spinnet", child: "Luna Lovegood"},
        {parent: "Alicia Spinnet", child: "Michael Corner"},
        {parent: "Alicia Spinnet", child: "Padma Patil"},
        {parent: "Alicia Spinnet", child: "Parvati Patil"},
        {parent: "Alicia Spinnet", child: "Ron Weasley"},
        {parent: "Alicia Spinnet", child: "Seamus Finnigan"},
        {parent: "Alicia Spinnet", child: "Susan Bones"},
        {parent: "Alicia Spinnet", child: "Terry Boot"},
        {parent: "Alicia Spinnet", child: "Zacharias Smith"},
        {parent: "Angelina Johnson", child: "Anthony Goldstein"},
        {parent: "Angelina Johnson", child: "Cho Chang"},
        {parent: "Angelina Johnson", child: "Colin Creevey"},
        {parent: "Angelina Johnson", child: "Dean Thomas"},
        {parent: "Angelina Johnson", child: "Dennis Creevey"},
        {parent: "Angelina Johnson", child: "Ernie Macmillian"},
        {parent: "Angelina Johnson", child: "Fred Weasley"},
        {parent: "Angelina Johnson", child: "George Weasley"},
        {parent: "Angelina Johnson", child: "Ginny Weasley"},
        {parent: "Angelina Johnson", child: "Hannah Abbott"},
        {parent: "Angelina Johnson", child: "Harry Potter"},
        {parent: "Angelina Johnson", child: "Hermione Granger"},
        {parent: "Angelina Johnson", child: "Justin Finch-Fletchley"},
        {parent: "Angelina Johnson", child: "Katie Bell"},
        {parent: "Angelina Johnson", child: "Lavender Brown"},
        {parent: "Angelina Johnson", child: "Lee Jordan"},
        {parent: "Angelina Johnson", child: "Luna Lovegood"},
        {parent: "Angelina Johnson", child: "Michael Corner"},
        {parent: "Angelina Johnson", child: "Neville Longbottom"},
        {parent: "Angelina Johnson", child: "Padma Patil"},
        {parent: "Angelina Johnson", child: "Parvati Patil"},
        {parent: "Angelina Johnson", child: "Ron Weasley"},
        {parent: "Angelina Johnson", child: "Seamus Finnigan"},
        {parent: "Angelina Johnson", child: "Susan Bones"},
        {parent: "Angelina Johnson", child: "Terry Boot"},
        {parent: "Angelina Johnson", child: "Zacharias Smith"},
        {parent: "Anthony Goldstein", child: "Cho Chang"},
        {parent: "Anthony Goldstein", child: "Colin Creevey"},
        {parent: "Anthony Goldstein", child: "Dean Thomas"},
        {parent: "Anthony Goldstein", child: "Dennis Creevey"},
        {parent: "Anthony Goldstein", child: "Ernie Macmillian"},
        {parent: "Anthony Goldstein", child: "Fred Weasley"},
        {parent: "Anthony Goldstein", child: "George Weasley"},
        {parent: "Anthony Goldstein", child: "Ginny Weasley"},
        {parent: "Anthony Goldstein", child: "Hannah Abbott"},
        {parent: "Anthony Goldstein", child: "Harry Potter"},
        {parent: "Anthony Goldstein", child: "Hermione Granger"},
        {parent: "Anthony Goldstein", child: "Justin Finch-Fletchley"},
        {parent: "Anthony Goldstein", child: "Katie Bell"},
        {parent: "Anthony Goldstein", child: "Lavender Brown"},
        {parent: "Anthony Goldstein", child: "Lee Jordan"},
        {parent: "Anthony Goldstein", child: "Luna Lovegood"},
        {parent: "Anthony Goldstein", child: "Michael Corner"},
        {parent: "Anthony Goldstein", child: "Neville Longbottom"},
        {parent: "Anthony Goldstein", child: "Padma Patil"},
        {parent: "Anthony Goldstein", child: "Parvati Patil"},
        {parent: "Anthony Goldstein", child: "Ron Weasley"},
        {parent: "Anthony Goldstein", child: "Seamus Finnigan"},
        {parent: "Anthony Goldstein", child: "Susan Bones"},
        {parent: "Anthony Goldstein", child: "Terry Boot"},
        {parent: "Anthony Goldstein", child: "Zacharias Smith"},
        {parent: "Cho Chang", child: "Colin Creevey"},
        {parent: "Cho Chang", child: "Dean Thomas"},
        {parent: "Cho Chang", child: "Dennis Creevey"},
        {parent: "Cho Chang", child: "Ernie Macmillian"},
        {parent: "Cho Chang", child: "Fred Weasley"},
        {parent: "Cho Chang", child: "George Weasley"},
        {parent: "Cho Chang", child: "Ginny Weasley"},
        {parent: "Cho Chang", child: "Hannah Abbott"},
        {parent: "Cho Chang", child: "Hermione Granger"},
        {parent: "Cho Chang", child: "Justin Finch-Fletchley"},
        {parent: "Cho Chang", child: "Katie Bell"},
        {parent: "Cho Chang", child: "Lavender Brown"},
        {parent: "Cho Chang", child: "Lee Jordan"},
        {parent: "Cho Chang", child: "Luna Lovegood"},
        {parent: "Cho Chang", child: "Neville Longbottom"},
        {parent: "Cho Chang", child: "Padma Patil"},
        {parent: "Cho Chang", child: "Parvati Patil"},
        {parent: "Cho Chang", child: "Ron Weasley"},
        {parent: "Cho Chang", child: "Seamus Finnigan"},
        {parent: "Cho Chang", child: "Susan Bones"},
        {parent: "Cho Chang", child: "Terry Boot"},
        {parent: "Cho Chang", child: "Zacharias Smith"},
        {parent: "Colin Creevey", child: "Dean Thomas"},
        {parent: "Colin Creevey", child: "Dennis Creevey"},
        {parent: "Colin Creevey", child: "Ernie Macmillian"},
        {parent: "Colin Creevey", child: "Fred Weasley"},
        {parent: "Colin Creevey", child: "George Weasley"},
        {parent: "Colin Creevey", child: "Ginny Weasley"},
        {parent: "Colin Creevey", child: "Hannah Abbott"},
        {parent: "Colin Creevey", child: "Harry Potter"},
        {parent: "Colin Creevey", child: "Hermione Granger"},
        {parent: "Colin Creevey", child: "Justin Finch-Fletchley"},
        {parent: "Colin Creevey", child: "Katie Bell"},
        {parent: "Colin Creevey", child: "Lavender Brown"},
        {parent: "Colin Creevey", child: "Lee Jordan"},
        {parent: "Colin Creevey", child: "Luna Lovegood"},
        {parent: "Colin Creevey", child: "Michael Corner"},
        {parent: "Colin Creevey", child: "Neville Longbottom"},
        {parent: "Colin Creevey", child: "Padma Patil"},
        {parent: "Colin Creevey", child: "Parvati Patil"},
        {parent: "Colin Creevey", child: "Ron Weasley"},
        {parent: "Colin Creevey", child: "Seamus Finnigan"},
        {parent: "Colin Creevey", child: "Susan Bones"},
        {parent: "Colin Creevey", child: "Terry Boot"},
        {parent: "Colin Creevey", child: "Zacharias Smith"},
        {parent: "Dean Thomas", child: "Dennis Creevey"},
        {parent: "Dean Thomas", child: "Ernie Macmillian"},
        {parent: "Dean Thomas", child: "Fred Weasley"},
        {parent: "Dean Thomas", child: "George Weasley"},
        {parent: "Dean Thomas", child: "Hannah Abbott"},
        {parent: "Dean Thomas", child: "Harry Potter"},
        {parent: "Dean Thomas", child: "Hermione Granger"},
        {parent: "Dean Thomas", child: "Justin Finch-Fletchley"},
        {parent: "Dean Thomas", child: "Katie Bell"},
        {parent: "Dean Thomas", child: "Lavender Brown"},
        {parent: "Dean Thomas", child: "Lee Jordan"},
        {parent: "Dean Thomas", child: "Luna Lovegood"},
        {parent: "Dean Thomas", child: "Michael Corner"},
        {parent: "Dean Thomas", child: "Neville Longbottom"},
        {parent: "Dean Thomas", child: "Padma Patil"},
        {parent: "Dean Thomas", child: "Parvati Patil"},
        {parent: "Dean Thomas", child: "Ron Weasley"},
        {parent: "Dean Thomas", child: "Seamus Finnigan"},
        {parent: "Dean Thomas", child: "Susan Bones"},
        {parent: "Dean Thomas", child: "Terry Boot"},
        {parent: "Dean Thomas", child: "Zacharias Smith"},
        {parent: "Ernie Macmillian", child: "Fred Weasley"},
        {parent: "Ernie Macmillian", child: "George Weasley"},
        {parent: "Ernie Macmillian", child: "Ginny Weasley"},
        {parent: "Ernie Macmillian", child: "Hannah Abbott"},
        {parent: "Ernie Macmillian", child: "Harry Potter"},
        {parent: "Ernie Macmillian", child: "Hermione Granger"},
        {parent: "Ernie Macmillian", child: "Justin Finch-Fletchley"},
        {parent: "Ernie Macmillian", child: "Katie Bell"},
        {parent: "Ernie Macmillian", child: "Lavender Brown"},
        {parent: "Ernie Macmillian", child: "Lee Jordan"},
        {parent: "Ernie Macmillian", child: "Luna Lovegood"},
        {parent: "Ernie Macmillian", child: "Michael Corner"},
        {parent: "Ernie Macmillian", child: "Neville Longbottom"},
        {parent: "Ernie Macmillian", child: "Padma Patil"},
        {parent: "Ernie Macmillian", child: "Parvati Patil"},
        {parent: "Ernie Macmillian", child: "Ron Weasley"},
        {parent: "Ernie Macmillian", child: "Seamus Finnigan"},
        {parent: "Ernie Macmillian", child: "Susan Bones"},
        {parent: "Ernie Macmillian", child: "Terry Boot"},
        {parent: "Ernie Macmillian", child: "Zacharias Smith"},
        {parent: "Fred Weasley", child: "Hannah Abbott"},
        {parent: "Fred Weasley", child: "Harry Potter"},
        {parent: "Fred Weasley", child: "Hermione Granger"},
        {parent: "Fred Weasley", child: "Justin Finch-Fletchley"},
        {parent: "Fred Weasley", child: "Katie Bell"},
        {parent: "Fred Weasley", child: "Lavender Brown"},
        {parent: "Fred Weasley", child: "Lee Jordan"},
        {parent: "Fred Weasley", child: "Luna Lovegood"},
        {parent: "Fred Weasley", child: "Michael Corner"},
        {parent: "Fred Weasley", child: "Neville Longbottom"},
        {parent: "Fred Weasley", child: "Padma Patil"},
        {parent: "Fred Weasley", child: "Parvati Patil"},
        {parent: "Fred Weasley", child: "Seamus Finnigan"},
        {parent: "Fred Weasley", child: "Susan Bones"},
        {parent: "Fred Weasley", child: "Terry Boot"},
        {parent: "Fred Weasley", child: "Zacharias Smith"},
        {parent: "George Weasley", child: "Hannah Abbott"},
        {parent: "George Weasley", child: "Harry Potter"},
        {parent: "George Weasley", child: "Hermione Granger"},
        {parent: "George Weasley", child: "Justin Finch-Fletchley"},
        {parent: "George Weasley", child: "Katie Bell"},
        {parent: "George Weasley", child: "Lavender Brown"},
        {parent: "George Weasley", child: "Lee Jordan"},
        {parent: "George Weasley", child: "Luna Lovegood"},
        {parent: "George Weasley", child: "Michael Corner"},
        {parent: "George Weasley", child: "Neville Longbottom"},
        {parent: "George Weasley", child: "Padma Patil"},
        {parent: "George Weasley", child: "Parvati Patil"},
        {parent: "George Weasley", child: "Seamus Finnigan"},
        {parent: "George Weasley", child: "Susan Bones"},
        {parent: "George Weasley", child: "Terry Boot"},
        {parent: "George Weasley", child: "Zacharias Smith"},
        {parent: "Ginny Weasley", child: "Hannah Abbott"},
        {parent: "Ginny Weasley", child: "Hermione Granger"},
        {parent: "Ginny Weasley", child: "Justin Finch-Fletchley"},
        {parent: "Ginny Weasley", child: "Katie Bell"},
        {parent: "Ginny Weasley", child: "Lavender Brown"},
        {parent: "Ginny Weasley", child: "Lee Jordan"},
        {parent: "Ginny Weasley", child: "Luna Lovegood"},
        {parent: "Ginny Weasley", child: "Neville Longbottom"},
        {parent: "Ginny Weasley", child: "Padma Patil"},
        {parent: "Ginny Weasley", child: "Parvati Patil"},
        {parent: "Ginny Weasley", child: "Seamus Finnigan"},
        {parent: "Ginny Weasley", child: "Susan Bones"},
        {parent: "Ginny Weasley", child: "Terry Boot"},
        {parent: "Ginny Weasley", child: "Zacharias Smith"},
        {parent: "Hannah Abbott", child: "Harry Potter"},
        {parent: "Hannah Abbott", child: "Hermione Granger"},
        {parent: "Hannah Abbott", child: "Justin Finch-Fletchley"},
        {parent: "Hannah Abbott", child: "Katie Bell"},
        {parent: "Hannah Abbott", child: "Lavender Brown"},
        {parent: "Hannah Abbott", child: "Lee Jordan"},
        {parent: "Hannah Abbott", child: "Luna Lovegood"},
        {parent: "Hannah Abbott", child: "Michael Corner"},
        {parent: "Hannah Abbott", child: "Neville Longbottom"},
        {parent: "Hannah Abbott", child: "Padma Patil"},
        {parent: "Hannah Abbott", child: "Parvati Patil"},
        {parent: "Hannah Abbott", child: "Ron Weasley"},
        {parent: "Hannah Abbott", child: "Seamus Finnigan"},
        {parent: "Hannah Abbott", child: "Susan Bones"},
        {parent: "Hannah Abbott", child: "Terry Boot"},
        {parent: "Hannah Abbott", child: "Zacharias Smith"},
        {parent: "Harry Potter", child: "Justin Finch-Fletchley"},
        {parent: "Harry Potter", child: "Katie Bell"},
        {parent: "Harry Potter", child: "Lavender Brown"},
        {parent: "Harry Potter", child: "Lee Jordan"},
        {parent: "Harry Potter", child: "Luna Lovegood"},
        {parent: "Harry Potter", child: "Michael Corner"},
        {parent: "Harry Potter", child: "Neville Longbottom"},
        {parent: "Harry Potter", child: "Padma Patil"},
        {parent: "Harry Potter", child: "Parvati Patil"},
        {parent: "Harry Potter", child: "Seamus Finnigan"},
        {parent: "Harry Potter", child: "Susan Bones"},
        {parent: "Harry Potter", child: "Terry Boot"},
        {parent: "Harry Potter", child: "Zacharias Smith"},
        {parent: "Hermione Granger", child: "Justin Finch-Fletchley"},
        {parent: "Hermione Granger", child: "Katie Bell"},
        {parent: "Hermione Granger", child: "Lavender Brown"},
        {parent: "Hermione Granger", child: "Lee Jordan"},
        {parent: "Hermione Granger", child: "Luna Lovegood"},
        {parent: "Hermione Granger", child: "Michael Corner"},
        {parent: "Hermione Granger", child: "Neville Longbottom"},
        {parent: "Hermione Granger", child: "Padma Patil"},
        {parent: "Hermione Granger", child: "Parvati Patil"},
        {parent: "Hermione Granger", child: "Seamus Finnigan"},
        {parent: "Hermione Granger", child: "Susan Bones"},
        {parent: "Hermione Granger", child: "Terry Boot"},
        {parent: "Hermione Granger", child: "Zacharias Smith"},
        {parent: "Justin Finch-Fletchley", child: "Katie Bell"},
        {parent: "Justin Finch-Fletchley", child: "Lavender Brown"},
        {parent: "Justin Finch-Fletchley", child: "Lee Jordan"},
        {parent: "Justin Finch-Fletchley", child: "Luna Lovegood"},
        {parent: "Justin Finch-Fletchley", child: "Michael Corner"},
        {parent: "Justin Finch-Fletchley", child: "Neville Longbottom"},
        {parent: "Justin Finch-Fletchley", child: "Padma Patil"},
        {parent: "Justin Finch-Fletchley", child: "Parvati Patil"},
        {parent: "Justin Finch-Fletchley", child: "Ron Weasley"},
        {parent: "Justin Finch-Fletchley", child: "Seamus Finnigan"},
        {parent: "Justin Finch-Fletchley", child: "Susan Bones"},
        {parent: "Justin Finch-Fletchley", child: "Terry Boot"},
        {parent: "Justin Finch-Fletchley", child: "Zacharias Smith"},
        {parent: "Katie Bell", child: "Lavender Brown"},
        {parent: "Katie Bell", child: "Lee Jordan"},
        {parent: "Katie Bell", child: "Luna Lovegood"},
        {parent: "Katie Bell", child: "Michael Corner"},
        {parent: "Katie Bell", child: "Neville Longbottom"},
        {parent: "Katie Bell", child: "Padma Patil"},
        {parent: "Katie Bell", child: "Parvati Patil"},
        {parent: "Katie Bell", child: "Ron Weasley"},
        {parent: "Katie Bell", child: "Seamus Finnigan"},
        {parent: "Katie Bell", child: "Susan Bones"},
        {parent: "Katie Bell", child: "Terry Boot"},
        {parent: "Katie Bell", child: "Zacharias Smith"},
        {parent: "Lavender Brown", child: "Lee Jordan"},
        {parent: "Lavender Brown", child: "Luna Lovegood"},
        {parent: "Lavender Brown", child: "Michael Corner"},
        {parent: "Lavender Brown", child: "Neville Longbottom"},
        {parent: "Lavender Brown", child: "Padma Patil"},
        {parent: "Lavender Brown", child: "Parvati Patil"},
        {parent: "Lavender Brown", child: "Ron Weasley"},
        {parent: "Lavender Brown", child: "Seamus Finnigan"},
        {parent: "Lavender Brown", child: "Susan Bones"},
        {parent: "Lavender Brown", child: "Terry Boot"},
        {parent: "Lavender Brown", child: "Zacharias Smith"},
        {parent: "Lee Jordan", child: "Luna Lovegood"},
        {parent: "Lee Jordan", child: "Michael Corner"},
        {parent: "Lee Jordan", child: "Neville Longbottom"},
        {parent: "Lee Jordan", child: "Padma Patil"},
        {parent: "Lee Jordan", child: "Parvati Patil"},
        {parent: "Lee Jordan", child: "Ron Weasley"},
        {parent: "Lee Jordan", child: "Seamus Finnigan"},
        {parent: "Lee Jordan", child: "Susan Bones"},
        {parent: "Lee Jordan", child: "Terry Boot"},
        {parent: "Lee Jordan", child: "Zacharias Smith"},
        {parent: "Luna Lovegood", child: "Michael Corner"},
        {parent: "Luna Lovegood", child: "Neville Longbottom"},
        {parent: "Luna Lovegood", child: "Padma Patil"},
        {parent: "Luna Lovegood", child: "Parvati Patil"},
        {parent: "Luna Lovegood", child: "Ron Weasley"},
        {parent: "Luna Lovegood", child: "Seamus Finnigan"},
        {parent: "Luna Lovegood", child: "Susan Bones"},
        {parent: "Luna Lovegood", child: "Terry Boot"},
        {parent: "Luna Lovegood", child: "Zacharias Smith"},
        {parent: "Michael Corner", child: "Neville Longbottom"},
        {parent: "Michael Corner", child: "Padma Patil"},
        {parent: "Michael Corner", child: "Parvati Patil"},
        {parent: "Michael Corner", child: "Ron Weasley"},
        {parent: "Michael Corner", child: "Seamus Finnigan"},
        {parent: "Michael Corner", child: "Susan Bones"},
        {parent: "Michael Corner", child: "Terry Boot"},
        {parent: "Michael Corner", child: "Zacharias Smith"},
        {parent: "Neville Longbottom", child: "Padma Patil"},
        {parent: "Neville Longbottom", child: "Parvati Patil"},
        {parent: "Neville Longbottom", child: "Ron Weasley"},
        {parent: "Neville Longbottom", child: "Seamus Finnigan"},
        {parent: "Neville Longbottom", child: "Susan Bones"},
        {parent: "Neville Longbottom", child: "Terry Boot"},
        {parent: "Neville Longbottom", child: "Zacharias Smith"},
        {parent: "Padma Patil", child: "Parvati Patil"},
        {parent: "Padma Patil", child: "Ron Weasley"},
        {parent: "Padma Patil", child: "Seamus Finnigan"},
        {parent: "Padma Patil", child: "Susan Bones"},
        {parent: "Padma Patil", child: "Terry Boot"},
        {parent: "Padma Patil", child: "Zacharias Smith"},
        {parent: "Parvati Patil", child: "Ron Weasley"},
        {parent: "Parvati Patil", child: "Seamus Finnigan"},
        {parent: "Parvati Patil", child: "Susan Bones"},
        {parent: "Parvati Patil", child: "Terry Boot"},
        {parent: "Parvati Patil", child: "Zacharias Smith"},
        {parent: "Ron Weasley", child: "Seamus Finnigan"},
        {parent: "Ron Weasley", child: "Susan Bones"},
        {parent: "Ron Weasley", child: "Terry Boot"},
        {parent: "Ron Weasley", child: "Zacharias Smith"},
        {parent: "Seamus Finnigan", child: "Susan Bones"},
        {parent: "Seamus Finnigan", child: "Terry Boot"},
        {parent: "Seamus Finnigan", child: "Zacharias Smith"},
        {parent: "Susan Bones", child: "Terry Boot"},
        {parent: "Susan Bones", child: "Zacharias Smith"},
        {parent: "Terry Boot", child: "Zacharias Smith"},
        {parent: "Alice Longbottom", child: "Neville Longbottom"},
        {parent: "Edgar Bones", child: "Susan Bones"},
        {parent: "Fabian Prewett", child: "Molly Weasley"},
        {parent: "Frank Longbottom", child: "Neville Longbottom"},
        {parent: "Frank Longbottom", child: "Bellatrix Lestrange"},
        {parent: "Gideon Prewett", child: "Molly Weasley"},
        {parent: "Nymphadora Tonks", child: "Bellatrix Lestrange"},
        {parent: "Aberforth Dumbledore", child: "Alastor Moody"},
        {parent: "Aberforth Dumbledore", child: "Alice Longbottom"},
        {parent: "Aberforth Dumbledore", child: "Arabella Figg"},
        {parent: "Aberforth Dumbledore", child: "Arthur Weasley"},
        {parent: "Aberforth Dumbledore", child: "Bill Weasley"},
        {parent: "Aberforth Dumbledore", child: "Caradoc Dearborn"},
        {parent: "Aberforth Dumbledore", child: "Charlie Weasley"},
        {parent: "Aberforth Dumbledore", child: "Dedalus Diggle"},
        {parent: "Aberforth Dumbledore", child: "Edgar Bones"},
        {parent: "Aberforth Dumbledore", child: "Elphias Doge"},
        {parent: "Aberforth Dumbledore", child: "Emmeline Vance"},
        {parent: "Aberforth Dumbledore", child: "Fabian Prewett"},
        {parent: "Aberforth Dumbledore", child: "Fleur Delacour"},
        {parent: "Aberforth Dumbledore", child: "Frank Longbottom"},
        {parent: "Aberforth Dumbledore", child: "Fred Weasley"},
        {parent: "Aberforth Dumbledore", child: "George Weasley"},
        {parent: "Aberforth Dumbledore", child: "Gideon Prewett"},
        {parent: "Aberforth Dumbledore", child: "Hestia Jones"},
        {parent: "Aberforth Dumbledore", child: "James Potter"},
        {parent: "Aberforth Dumbledore", child: "Kingsley Shacklebolt"},
        {parent: "Aberforth Dumbledore", child: "Lily Potter"},
        {parent: "Aberforth Dumbledore", child: "Marlene McKinnon"},
        {parent: "Aberforth Dumbledore", child: "Molly Weasley"},
        {parent: "Aberforth Dumbledore", child: "Mundungus Fletcher"},
        {parent: "Aberforth Dumbledore", child: "Nymphadora Tonks"},
        {parent: "Aberforth Dumbledore", child: "Professor McGonagall"},
        {parent: "Aberforth Dumbledore", child: "Remus Lupin"},
        {parent: "Aberforth Dumbledore", child: "Rubeus Hagrid"},
        {parent: "Aberforth Dumbledore", child: "Sirius Black"},
        {parent: "Aberforth Dumbledore", child: "Sturgis Podmore"},
        {parent: "Alastor Moody", child: "Albus Dumbledore"},
        {parent: "Alastor Moody", child: "Alice Longbottom"},
        {parent: "Alastor Moody", child: "Arabella Figg"},
        {parent: "Alastor Moody", child: "Arthur Weasley"},
        {parent: "Alastor Moody", child: "Bill Weasley"},
        {parent: "Alastor Moody", child: "Caradoc Dearborn"},
        {parent: "Alastor Moody", child: "Charlie Weasley"},
        {parent: "Alastor Moody", child: "Dedalus Diggle"},
        {parent: "Alastor Moody", child: "Edgar Bones"},
        {parent: "Alastor Moody", child: "Elphias Doge"},
        {parent: "Alastor Moody", child: "Emmeline Vance"},
        {parent: "Alastor Moody", child: "Fabian Prewett"},
        {parent: "Alastor Moody", child: "Fleur Delacour"},
        {parent: "Alastor Moody", child: "Frank Longbottom"},
        {parent: "Alastor Moody", child: "Fred Weasley"},
        {parent: "Alastor Moody", child: "George Weasley"},
        {parent: "Alastor Moody", child: "Gideon Prewett"},
        {parent: "Alastor Moody", child: "Hestia Jones"},
        {parent: "Alastor Moody", child: "James Potter"},
        {parent: "Alastor Moody", child: "Kingsley Shacklebolt"},
        {parent: "Alastor Moody", child: "Lily Potter"},
        {parent: "Alastor Moody", child: "Marlene McKinnon"},
        {parent: "Alastor Moody", child: "Molly Weasley"},
        {parent: "Alastor Moody", child: "Mundungus Fletcher"},
        {parent: "Alastor Moody", child: "Nymphadora Tonks"},
        {parent: "Alastor Moody", child: "Professor McGonagall"},
        {parent: "Alastor Moody", child: "Remus Lupin"},
        {parent: "Alastor Moody", child: "Rubeus Hagrid"},
        {parent: "Alastor Moody", child: "Sirius Black"},
        {parent: "Alastor Moody", child: "Sturgis Podmore"},
        {parent: "Albus Dumbledore", child: "Alice Longbottom"},
        {parent: "Albus Dumbledore", child: "Arabella Figg"},
        {parent: "Albus Dumbledore", child: "Arthur Weasley"},
        {parent: "Albus Dumbledore", child: "Bill Weasley"},
        {parent: "Albus Dumbledore", child: "Caradoc Dearborn"},
        {parent: "Albus Dumbledore", child: "Charlie Weasley"},
        {parent: "Albus Dumbledore", child: "Dedalus Diggle"},
        {parent: "Albus Dumbledore", child: "Edgar Bones"},
        {parent: "Albus Dumbledore", child: "Emmeline Vance"},
        {parent: "Albus Dumbledore", child: "Fabian Prewett"},
        {parent: "Albus Dumbledore", child: "Fleur Delacour"},
        {parent: "Albus Dumbledore", child: "Frank Longbottom"},
        {parent: "Albus Dumbledore", child: "Fred Weasley"},
        {parent: "Albus Dumbledore", child: "George Weasley"},
        {parent: "Albus Dumbledore", child: "Gideon Prewett"},
        {parent: "Albus Dumbledore", child: "Hestia Jones"},
        {parent: "Albus Dumbledore", child: "James Potter"},
        {parent: "Albus Dumbledore", child: "Kingsley Shacklebolt"},
        {parent: "Albus Dumbledore", child: "Lily Potter"},
        {parent: "Albus Dumbledore", child: "Marlene McKinnon"},
        {parent: "Albus Dumbledore", child: "Molly Weasley"},
        {parent: "Albus Dumbledore", child: "Mundungus Fletcher"},
        {parent: "Albus Dumbledore", child: "Nymphadora Tonks"},
        {parent: "Albus Dumbledore", child: "Professor McGonagall"},
        {parent: "Albus Dumbledore", child: "Remus Lupin"},
        {parent: "Albus Dumbledore", child: "Rubeus Hagrid"},
        {parent: "Albus Dumbledore", child: "Sirius Black"},
        {parent: "Albus Dumbledore", child: "Sturgis Podmore"},
        {parent: "Alice Longbottom", child: "Arabella Figg"},
        {parent: "Alice Longbottom", child: "Arthur Weasley"},
        {parent: "Alice Longbottom", child: "Bill Weasley"},
        {parent: "Alice Longbottom", child: "Caradoc Dearborn"},
        {parent: "Alice Longbottom", child: "Charlie Weasley"},
        {parent: "Alice Longbottom", child: "Dedalus Diggle"},
        {parent: "Alice Longbottom", child: "Edgar Bones"},
        {parent: "Alice Longbottom", child: "Emmeline Vance"},
        {parent: "Alice Longbottom", child: "Fabian Prewett"},
        {parent: "Alice Longbottom", child: "Fleur Delacour"},
        {parent: "Alice Longbottom", child: "Frank Longbottom"},
        {parent: "Alice Longbottom", child: "Fred Weasley"},
        {parent: "Alice Longbottom", child: "George Weasley"},
        {parent: "Alice Longbottom", child: "Gideon Prewett"},
        {parent: "Alice Longbottom", child: "Hestia Jones"},
        {parent: "Alice Longbottom", child: "James Potter"},
        {parent: "Alice Longbottom", child: "Kingsley Shacklebolt"},
        {parent: "Alice Longbottom", child: "Lily Potter"},
        {parent: "Alice Longbottom", child: "Marlene McKinnon"},
        {parent: "Alice Longbottom", child: "Molly Weasley"},
        {parent: "Alice Longbottom", child: "Mundungus Fletcher"},
        {parent: "Alice Longbottom", child: "Nymphadora Tonks"},
        {parent: "Alice Longbottom", child: "Professor McGonagall"},
        {parent: "Alice Longbottom", child: "Remus Lupin"},
        {parent: "Alice Longbottom", child: "Rubeus Hagrid"},
        {parent: "Alice Longbottom", child: "Sirius Black"},
        {parent: "Alice Longbottom", child: "Sturgis Podmore"},
        {parent: "Arabella Figg", child: "Arthur Weasley"},
        {parent: "Arabella Figg", child: "Bill Weasley"},
        {parent: "Arabella Figg", child: "Caradoc Dearborn"},
        {parent: "Arabella Figg", child: "Charlie Weasley"},
        {parent: "Arabella Figg", child: "Dedalus Diggle"},
        {parent: "Arabella Figg", child: "Edgar Bones"},
        {parent: "Arabella Figg", child: "Emmeline Vance"},
        {parent: "Arabella Figg", child: "Fabian Prewett"},
        {parent: "Arabella Figg", child: "Fleur Delacour"},
        {parent: "Arabella Figg", child: "Frank Longbottom"},
        {parent: "Arabella Figg", child: "Fred Weasley"},
        {parent: "Arabella Figg", child: "George Weasley"},
        {parent: "Arabella Figg", child: "Gideon Prewett"},
        {parent: "Arabella Figg", child: "Hestia Jones"},
        {parent: "Arabella Figg", child: "James Potter"},
        {parent: "Arabella Figg", child: "Kingsley Shacklebolt"},
        {parent: "Arabella Figg", child: "Lily Potter"},
        {parent: "Arabella Figg", child: "Marlene McKinnon"},
        {parent: "Arabella Figg", child: "Molly Weasley"},
        {parent: "Arabella Figg", child: "Mundungus Fletcher"},
        {parent: "Arabella Figg", child: "Nymphadora Tonks"},
        {parent: "Arabella Figg", child: "Professor McGonagall"},
        {parent: "Arabella Figg", child: "Remus Lupin"},
        {parent: "Arabella Figg", child: "Rubeus Hagrid"},
        {parent: "Arabella Figg", child: "Sirius Black"},
        {parent: "Arabella Figg", child: "Sturgis Podmore"},
        {parent: "Arthur Weasley", child: "Caradoc Dearborn"},
        {parent: "Arthur Weasley", child: "Dedalus Diggle"},
        {parent: "Arthur Weasley", child: "Edgar Bones"},
        {parent: "Arthur Weasley", child: "Emmeline Vance"},
        {parent: "Arthur Weasley", child: "Fabian Prewett"},
        {parent: "Arthur Weasley", child: "Fleur Delacour"},
        {parent: "Arthur Weasley", child: "Frank Longbottom"},
        {parent: "Arthur Weasley", child: "Gideon Prewett"},
        {parent: "Arthur Weasley", child: "Hestia Jones"},
        {parent: "Arthur Weasley", child: "James Potter"},
        {parent: "Arthur Weasley", child: "Kingsley Shacklebolt"},
        {parent: "Arthur Weasley", child: "Lily Potter"},
        {parent: "Arthur Weasley", child: "Marlene McKinnon"},
        {parent: "Arthur Weasley", child: "Mundungus Fletcher"},
        {parent: "Arthur Weasley", child: "Nymphadora Tonks"},
        {parent: "Arthur Weasley", child: "Professor McGonagall"},
        {parent: "Arthur Weasley", child: "Remus Lupin"},
        {parent: "Arthur Weasley", child: "Rubeus Hagrid"},
        {parent: "Arthur Weasley", child: "Sirius Black"},
        {parent: "Arthur Weasley", child: "Sturgis Podmore"},
        {parent: "Bill Weasley", child: "Caradoc Dearborn"},
        {parent: "Bill Weasley", child: "Dedalus Diggle"},
        {parent: "Bill Weasley", child: "Edgar Bones"},
        {parent: "Bill Weasley", child: "Emmeline Vance"},
        {parent: "Bill Weasley", child: "Fabian Prewett"},
        {parent: "Bill Weasley", child: "Fleur Delacour"},
        {parent: "Bill Weasley", child: "Frank Longbottom"},
        {parent: "Bill Weasley", child: "Gideon Prewett"},
        {parent: "Bill Weasley", child: "Hestia Jones"},
        {parent: "Bill Weasley", child: "James Potter"},
        {parent: "Bill Weasley", child: "Kingsley Shacklebolt"},
        {parent: "Bill Weasley", child: "Lily Potter"},
        {parent: "Bill Weasley", child: "Marlene McKinnon"},
        {parent: "Bill Weasley", child: "Mundungus Fletcher"},
        {parent: "Bill Weasley", child: "Nymphadora Tonks"},
        {parent: "Bill Weasley", child: "Professor McGonagall"},
        {parent: "Bill Weasley", child: "Remus Lupin"},
        {parent: "Bill Weasley", child: "Rubeus Hagrid"},
        {parent: "Bill Weasley", child: "Sirius Black"},
        {parent: "Bill Weasley", child: "Sturgis Podmore"},
        {parent: "Caradoc Dearborn", child: "Charlie Weasley"},
        {parent: "Caradoc Dearborn", child: "Dedalus Diggle"},
        {parent: "Caradoc Dearborn", child: "Edgar Bones"},
        {parent: "Caradoc Dearborn", child: "Emmeline Vance"},
        {parent: "Caradoc Dearborn", child: "Fabian Prewett"},
        {parent: "Caradoc Dearborn", child: "Fleur Delacour"},
        {parent: "Caradoc Dearborn", child: "Frank Longbottom"},
        {parent: "Caradoc Dearborn", child: "Fred Weasley"},
        {parent: "Caradoc Dearborn", child: "George Weasley"},
        {parent: "Caradoc Dearborn", child: "Gideon Prewett"},
        {parent: "Caradoc Dearborn", child: "Hestia Jones"},
        {parent: "Caradoc Dearborn", child: "James Potter"},
        {parent: "Caradoc Dearborn", child: "Kingsley Shacklebolt"},
        {parent: "Caradoc Dearborn", child: "Lily Potter"},
        {parent: "Caradoc Dearborn", child: "Marlene McKinnon"},
        {parent: "Caradoc Dearborn", child: "Molly Weasley"},
        {parent: "Caradoc Dearborn", child: "Mundungus Fletcher"},
        {parent: "Caradoc Dearborn", child: "Nymphadora Tonks"},
        {parent: "Caradoc Dearborn", child: "Professor McGonagall"},
        {parent: "Caradoc Dearborn", child: "Remus Lupin"},
        {parent: "Caradoc Dearborn", child: "Rubeus Hagrid"},
        {parent: "Caradoc Dearborn", child: "Sirius Black"},
        {parent: "Caradoc Dearborn", child: "Sturgis Podmore"},
        {parent: "Charlie Weasley", child: "Dedalus Diggle"},
        {parent: "Charlie Weasley", child: "Edgar Bones"},
        {parent: "Charlie Weasley", child: "Emmeline Vance"},
        {parent: "Charlie Weasley", child: "Fabian Prewett"},
        {parent: "Charlie Weasley", child: "Fleur Delacour"},
        {parent: "Charlie Weasley", child: "Frank Longbottom"},
        {parent: "Charlie Weasley", child: "Gideon Prewett"},
        {parent: "Charlie Weasley", child: "Hestia Jones"},
        {parent: "Charlie Weasley", child: "James Potter"},
        {parent: "Charlie Weasley", child: "Kingsley Shacklebolt"},
        {parent: "Charlie Weasley", child: "Lily Potter"},
        {parent: "Charlie Weasley", child: "Marlene McKinnon"},
        {parent: "Charlie Weasley", child: "Mundungus Fletcher"},
        {parent: "Charlie Weasley", child: "Nymphadora Tonks"},
        {parent: "Charlie Weasley", child: "Professor McGonagall"},
        {parent: "Charlie Weasley", child: "Remus Lupin"},
        {parent: "Charlie Weasley", child: "Rubeus Hagrid"},
        {parent: "Charlie Weasley", child: "Sirius Black"},
        {parent: "Charlie Weasley", child: "Sturgis Podmore"},
        {parent: "Dedalus Diggle", child: "Edgar Bones"},
        {parent: "Dedalus Diggle", child: "Emmeline Vance"},
        {parent: "Dedalus Diggle", child: "Fabian Prewett"},
        {parent: "Dedalus Diggle", child: "Fleur Delacour"},
        {parent: "Dedalus Diggle", child: "Frank Longbottom"},
        {parent: "Dedalus Diggle", child: "Fred Weasley"},
        {parent: "Dedalus Diggle", child: "George Weasley"},
        {parent: "Dedalus Diggle", child: "Gideon Prewett"},
        {parent: "Dedalus Diggle", child: "Hestia Jones"},
        {parent: "Dedalus Diggle", child: "James Potter"},
        {parent: "Dedalus Diggle", child: "Kingsley Shacklebolt"},
        {parent: "Dedalus Diggle", child: "Lily Potter"},
        {parent: "Dedalus Diggle", child: "Marlene McKinnon"},
        {parent: "Dedalus Diggle", child: "Molly Weasley"},
        {parent: "Dedalus Diggle", child: "Mundungus Fletcher"},
        {parent: "Dedalus Diggle", child: "Nymphadora Tonks"},
        {parent: "Dedalus Diggle", child: "Professor McGonagall"},
        {parent: "Dedalus Diggle", child: "Remus Lupin"},
        {parent: "Dedalus Diggle", child: "Rubeus Hagrid"},
        {parent: "Dedalus Diggle", child: "Sirius Black"},
        {parent: "Dedalus Diggle", child: "Sturgis Podmore"},
        {parent: "Edgar Bones", child: "Emmeline Vance"},
        {parent: "Edgar Bones", child: "Fabian Prewett"},
        {parent: "Edgar Bones", child: "Fleur Delacour"},
        {parent: "Edgar Bones", child: "Frank Longbottom"},
        {parent: "Edgar Bones", child: "Fred Weasley"},
        {parent: "Edgar Bones", child: "George Weasley"},
        {parent: "Edgar Bones", child: "Gideon Prewett"},
        {parent: "Edgar Bones", child: "Hestia Jones"},
        {parent: "Edgar Bones", child: "James Potter"},
        {parent: "Edgar Bones", child: "Kingsley Shacklebolt"},
        {parent: "Edgar Bones", child: "Lily Potter"},
        {parent: "Edgar Bones", child: "Marlene McKinnon"},
        {parent: "Edgar Bones", child: "Molly Weasley"},
        {parent: "Edgar Bones", child: "Mundungus Fletcher"},
        {parent: "Edgar Bones", child: "Nymphadora Tonks"},
        {parent: "Edgar Bones", child: "Professor McGonagall"},
        {parent: "Edgar Bones", child: "Remus Lupin"},
        {parent: "Edgar Bones", child: "Rubeus Hagrid"},
        {parent: "Edgar Bones", child: "Sirius Black"},
        {parent: "Edgar Bones", child: "Sturgis Podmore"},
        {parent: "Emmeline Vance", child: "Fabian Prewett"},
        {parent: "Emmeline Vance", child: "Fleur Delacour"},
        {parent: "Emmeline Vance", child: "Frank Longbottom"},
        {parent: "Emmeline Vance", child: "Fred Weasley"},
        {parent: "Emmeline Vance", child: "George Weasley"},
        {parent: "Emmeline Vance", child: "Gideon Prewett"},
        {parent: "Emmeline Vance", child: "Hestia Jones"},
        {parent: "Emmeline Vance", child: "James Potter"},
        {parent: "Emmeline Vance", child: "Kingsley Shacklebolt"},
        {parent: "Emmeline Vance", child: "Lily Potter"},
        {parent: "Emmeline Vance", child: "Marlene McKinnon"},
        {parent: "Emmeline Vance", child: "Molly Weasley"},
        {parent: "Emmeline Vance", child: "Mundungus Fletcher"},
        {parent: "Emmeline Vance", child: "Nymphadora Tonks"},
        {parent: "Emmeline Vance", child: "Professor McGonagall"},
        {parent: "Emmeline Vance", child: "Remus Lupin"},
        {parent: "Emmeline Vance", child: "Rubeus Hagrid"},
        {parent: "Emmeline Vance", child: "Sirius Black"},
        {parent: "Emmeline Vance", child: "Sturgis Podmore"},
        {parent: "Fabian Prewett", child: "Fleur Delacour"},
        {parent: "Fabian Prewett", child: "Frank Longbottom"},
        {parent: "Fabian Prewett", child: "Fred Weasley"},
        {parent: "Fabian Prewett", child: "George Weasley"},
        {parent: "Fabian Prewett", child: "Gideon Prewett"},
        {parent: "Fabian Prewett", child: "Hestia Jones"},
        {parent: "Fabian Prewett", child: "James Potter"},
        {parent: "Fabian Prewett", child: "Kingsley Shacklebolt"},
        {parent: "Fabian Prewett", child: "Lily Potter"},
        {parent: "Fabian Prewett", child: "Marlene McKinnon"},
        {parent: "Fabian Prewett", child: "Mundungus Fletcher"},
        {parent: "Fabian Prewett", child: "Nymphadora Tonks"},
        {parent: "Fabian Prewett", child: "Professor McGonagall"},
        {parent: "Fabian Prewett", child: "Remus Lupin"},
        {parent: "Fabian Prewett", child: "Rubeus Hagrid"},
        {parent: "Fabian Prewett", child: "Sirius Black"},
        {parent: "Fabian Prewett", child: "Sturgis Podmore"},
        {parent: "Fleur Delacour", child: "Frank Longbottom"},
        {parent: "Fleur Delacour", child: "Fred Weasley"},
        {parent: "Fleur Delacour", child: "George Weasley"},
        {parent: "Fleur Delacour", child: "Gideon Prewett"},
        {parent: "Fleur Delacour", child: "Hestia Jones"},
        {parent: "Fleur Delacour", child: "James Potter"},
        {parent: "Fleur Delacour", child: "Kingsley Shacklebolt"},
        {parent: "Fleur Delacour", child: "Lily Potter"},
        {parent: "Fleur Delacour", child: "Marlene McKinnon"},
        {parent: "Fleur Delacour", child: "Molly Weasley"},
        {parent: "Fleur Delacour", child: "Mundungus Fletcher"},
        {parent: "Fleur Delacour", child: "Nymphadora Tonks"},
        {parent: "Fleur Delacour", child: "Professor McGonagall"},
        {parent: "Fleur Delacour", child: "Remus Lupin"},
        {parent: "Fleur Delacour", child: "Rubeus Hagrid"},
        {parent: "Fleur Delacour", child: "Sirius Black"},
        {parent: "Fleur Delacour", child: "Sturgis Podmore"},
        {parent: "Frank Longbottom", child: "Fred Weasley"},
        {parent: "Frank Longbottom", child: "George Weasley"},
        {parent: "Frank Longbottom", child: "Gideon Prewett"},
        {parent: "Frank Longbottom", child: "Hestia Jones"},
        {parent: "Frank Longbottom", child: "James Potter"},
        {parent: "Frank Longbottom", child: "Kingsley Shacklebolt"},
        {parent: "Frank Longbottom", child: "Lily Potter"},
        {parent: "Frank Longbottom", child: "Marlene McKinnon"},
        {parent: "Frank Longbottom", child: "Molly Weasley"},
        {parent: "Frank Longbottom", child: "Mundungus Fletcher"},
        {parent: "Frank Longbottom", child: "Nymphadora Tonks"},
        {parent: "Frank Longbottom", child: "Professor McGonagall"},
        {parent: "Frank Longbottom", child: "Remus Lupin"},
        {parent: "Frank Longbottom", child: "Rubeus Hagrid"},
        {parent: "Frank Longbottom", child: "Sirius Black"},
        {parent: "Frank Longbottom", child: "Sturgis Podmore"},
        {parent: "Fred Weasley", child: "Gideon Prewett"},
        {parent: "Fred Weasley", child: "Hestia Jones"},
        {parent: "Fred Weasley", child: "James Potter"},
        {parent: "Fred Weasley", child: "Kingsley Shacklebolt"},
        {parent: "Fred Weasley", child: "Lily Potter"},
        {parent: "Fred Weasley", child: "Marlene McKinnon"},
        {parent: "Fred Weasley", child: "Mundungus Fletcher"},
        {parent: "Fred Weasley", child: "Nymphadora Tonks"},
        {parent: "Fred Weasley", child: "Professor McGonagall"},
        {parent: "Fred Weasley", child: "Remus Lupin"},
        {parent: "Fred Weasley", child: "Rubeus Hagrid"},
        {parent: "Fred Weasley", child: "Sirius Black"},
        {parent: "Fred Weasley", child: "Sturgis Podmore"},
        {parent: "George Weasley", child: "Gideon Prewett"},
        {parent: "George Weasley", child: "Hestia Jones"},
        {parent: "George Weasley", child: "James Potter"},
        {parent: "George Weasley", child: "Kingsley Shacklebolt"},
        {parent: "George Weasley", child: "Lily Potter"},
        {parent: "George Weasley", child: "Marlene McKinnon"},
        {parent: "George Weasley", child: "Mundungus Fletcher"},
        {parent: "George Weasley", child: "Nymphadora Tonks"},
        {parent: "George Weasley", child: "Professor McGonagall"},
        {parent: "George Weasley", child: "Remus Lupin"},
        {parent: "George Weasley", child: "Rubeus Hagrid"},
        {parent: "George Weasley", child: "Sirius Black"},
        {parent: "George Weasley", child: "Sturgis Podmore"},
        {parent: "Gideon Prewett", child: "Hestia Jones"},
        {parent: "Gideon Prewett", child: "James Potter"},
        {parent: "Gideon Prewett", child: "Kingsley Shacklebolt"},
        {parent: "Gideon Prewett", child: "Lily Potter"},
        {parent: "Gideon Prewett", child: "Marlene McKinnon"},
        {parent: "Gideon Prewett", child: "Molly Weasley"},
        {parent: "Gideon Prewett", child: "Mundungus Fletcher"},
        {parent: "Gideon Prewett", child: "Nymphadora Tonks"},
        {parent: "Gideon Prewett", child: "Professor McGonagall"},
        {parent: "Gideon Prewett", child: "Remus Lupin"},
        {parent: "Gideon Prewett", child: "Rubeus Hagrid"},
        {parent: "Gideon Prewett", child: "Sirius Black"},
        {parent: "Gideon Prewett", child: "Sturgis Podmore"},
        {parent: "Hestia Jones", child: "James Potter"},
        {parent: "Hestia Jones", child: "Kingsley Shacklebolt"},
        {parent: "Hestia Jones", child: "Lily Potter"},
        {parent: "Hestia Jones", child: "Marlene McKinnon"},
        {parent: "Hestia Jones", child: "Molly Weasley"},
        {parent: "Hestia Jones", child: "Mundungus Fletcher"},
        {parent: "Hestia Jones", child: "Nymphadora Tonks"},
        {parent: "Hestia Jones", child: "Professor McGonagall"},
        {parent: "Hestia Jones", child: "Remus Lupin"},
        {parent: "Hestia Jones", child: "Rubeus Hagrid"},
        {parent: "Hestia Jones", child: "Sirius Black"},
        {parent: "Hestia Jones", child: "Sturgis Podmore"},
        {parent: "James Potter", child: "Kingsley Shacklebolt"},
        {parent: "James Potter", child: "Marlene McKinnon"},
        {parent: "James Potter", child: "Molly Weasley"},
        {parent: "James Potter", child: "Mundungus Fletcher"},
        {parent: "James Potter", child: "Nymphadora Tonks"},
        {parent: "James Potter", child: "Professor McGonagall"},
        {parent: "James Potter", child: "Remus Lupin"},
        {parent: "James Potter", child: "Rubeus Hagrid"},
        {parent: "James Potter", child: "Sirius Black"},
        {parent: "James Potter", child: "Sturgis Podmore"},
        {parent: "Kingsley Shacklebolt", child: "Lily Potter"},
        {parent: "Kingsley Shacklebolt", child: "Marlene McKinnon"},
        {parent: "Kingsley Shacklebolt", child: "Molly Weasley"},
        {parent: "Kingsley Shacklebolt", child: "Mundungus Fletcher"},
        {parent: "Kingsley Shacklebolt", child: "Nymphadora Tonks"},
        {parent: "Kingsley Shacklebolt", child: "Professor McGonagall"},
        {parent: "Kingsley Shacklebolt", child: "Remus Lupin"},
        {parent: "Kingsley Shacklebolt", child: "Rubeus Hagrid"},
        {parent: "Kingsley Shacklebolt", child: "Sirius Black"},
        {parent: "Kingsley Shacklebolt", child: "Sturgis Podmore"},
        {parent: "Lily Potter", child: "Marlene McKinnon"},
        {parent: "Lily Potter", child: "Molly Weasley"},
        {parent: "Lily Potter", child: "Mundungus Fletcher"},
        {parent: "Lily Potter", child: "Nymphadora Tonks"},
        {parent: "Lily Potter", child: "Professor McGonagall"},
        {parent: "Lily Potter", child: "Remus Lupin"},
        {parent: "Lily Potter", child: "Rubeus Hagrid"},
        {parent: "Lily Potter", child: "Sirius Black"},
        {parent: "Lily Potter", child: "Sturgis Podmore"},
        {parent: "Marlene McKinnon", child: "Molly Weasley"},
        {parent: "Marlene McKinnon", child: "Mundungus Fletcher"},
        {parent: "Marlene McKinnon", child: "Nymphadora Tonks"},
        {parent: "Marlene McKinnon", child: "Professor McGonagall"},
        {parent: "Marlene McKinnon", child: "Remus Lupin"},
        {parent: "Marlene McKinnon", child: "Rubeus Hagrid"},
        {parent: "Marlene McKinnon", child: "Sirius Black"},
        {parent: "Marlene McKinnon", child: "Sturgis Podmore"},
        {parent: "Molly Weasley", child: "Mundungus Fletcher"},
        {parent: "Molly Weasley", child: "Nymphadora Tonks"},
        {parent: "Molly Weasley", child: "Professor McGonagall"},
        {parent: "Molly Weasley", child: "Remus Lupin"},
        {parent: "Molly Weasley", child: "Rubeus Hagrid"},
        {parent: "Molly Weasley", child: "Sirius Black"},
        {parent: "Molly Weasley", child: "Sturgis Podmore"},
        {parent: "Mundungus Fletcher", child: "Nymphadora Tonks"},
        {parent: "Mundungus Fletcher", child: "Professor McGonagall"},
        {parent: "Mundungus Fletcher", child: "Remus Lupin"},
        {parent: "Mundungus Fletcher", child: "Rubeus Hagrid"},
        {parent: "Mundungus Fletcher", child: "Sirius Black"},
        {parent: "Mundungus Fletcher", child: "Sturgis Podmore"},
        {parent: "Nymphadora Tonks", child: "Professor McGonagall"},
        {parent: "Nymphadora Tonks", child: "Remus Lupin"},
        {parent: "Nymphadora Tonks", child: "Rubeus Hagrid"},
        {parent: "Nymphadora Tonks", child: "Sirius Black"},
        {parent: "Nymphadora Tonks", child: "Sturgis Podmore"},
        {parent: "Professor McGonagall", child: "Remus Lupin"},
        {parent: "Professor McGonagall", child: "Rubeus Hagrid"},
        {parent: "Professor McGonagall", child: "Sirius Black"},
        {parent: "Professor McGonagall", child: "Sturgis Podmore"},
        {parent: "Remus Lupin", child: "Rubeus Hagrid"},
        {parent: "Remus Lupin", child: "Sirius Black"},
        {parent: "Remus Lupin", child: "Sturgis Podmore"},
        {parent: "Rubeus Hagrid", child: "Sirius Black"},
        {parent: "Rubeus Hagrid", child: "Sturgis Podmore"},
        {parent: "Sirius Black", child: "Sturgis Podmore"},
        {parent: "Voldemort", child: "Draco Malfoy"},
        {parent: "Voldemort", child: "Lucius Malfoy"},
        {parent: "Voldemort", child: "Colin Creevey"},
        {parent: "Voldemort", child: "Edgar Bones"},
        {parent: "Voldemort", child: "Emmeline Vance"},
        {parent: "Voldemort", child: "Fabian Prewett"},
        {parent: "Voldemort", child: "Fred Weasley"},
        {parent: "Voldemort", child: "Gideon Prewett"},
        {parent: "Voldemort", child: "Hedwig"},
        {parent: "Voldemort", child: "Nymphadora Tonks"},
        {parent: "Voldemort", child: "Remus Lupin"},
      ],
    }
  }

  render() {
    return(
      <div className="container"
        style={{textAlign:"center",fontFamily:"Open Sans"}}>
        <h1 style={{textAlign: "center"}}>Network Chart</h1>
        <NetworkChart nodes={this.state.nodes} links={this.state.links}
          labelKey="name" groupKey="group" />
      </div>
    )
  }
}


ReactDOM.render(
  <ExampleApp />,
  document.getElementById("react-app")
)
